### ISSUE TITLE
Declare transactions break Checkpoint

### ISSUE THREAD

**Issue by rzmahmood** [snapshot-labs/checkpoint#68]
https://goerli.voyager.online/tx/0x5bb78505f5f9204a456441640a7500573baea68d6f0fad90589dfd826af4e3a

The following error occurs:
```
{"level":30,"time":1656308724920,"component":"checkpoint","blockNumber":241369,"msg":"handling block"}
/Users/.../starknet-asset-indexer/node_modules/starknet/utils/address.js:13
    throw new Error('Invalid Address Type');
          ^
Error: Invalid Address Type
    at validateAndParseAddress (/Users/.../starknet-asset-indexer/node_modules/starknet/utils/address.js:13:11)
    at Checkpoint.handleTx (/Users/.../starknet-asset-indexer/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:217:68)
    at Checkpoint.handleBlock (/Users/.../starknet-asset-indexer/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:208:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Checkpoint.next (/Users/.../starknet-asset-indexer/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:179:9)
    at async Checkpoint.start (/Users/.../starknet-asset-indexer/node_modules/@snapshot-labs/checkpoint/dist/src/checkpoint.js:109:16)
```

It is because Checkpoint attempt to `validateAndParseAddress` on the contract address. Declare transactions do not have a contract address and therefore breaks Checkpoint.

**Comment by bonustrack** [comment]
Here is the block with declare tx https://alpha4.starknet.io/feeder_gateway/get_block?blockNumber=241369
